import os
import datetime

OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "output"
)


def generate_report(api_name, ssn_result, stub_result, intelligence_result):
    api     = api_name
    ssn     = ssn_result["ssn"]
    ssn_hex = ssn_result["ssn_hex"]
    build   = ssn_result["build"]
    conf    = intelligence_result["confidence"]
    risks   = intelligence_result["risks"]
    dets    = intelligence_result["detections"]
    maps    = intelligence_result["mappings"]
    imps    = intelligence_result["improvements"]
    ts      = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    L = []
    L.append("# SilentGate Evasion Report")
    L.append("## API: " + api)
    L.append("")
    L.append("**Generated by:** SilentGate v1.0.0")
    L.append("**Author:** JarDani")
    L.append("**Date:** " + ts)
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 1. Overview")
    L.append("")
    L.append("| Field | Value |")
    L.append("|-------|-------|")
    L.append("| Target API | " + api + " |")
    L.append("| SSN decimal | " + str(ssn) + " |")
    L.append("| SSN hex | " + ssn_hex + " |")
    L.append("| Architecture | x64 |")
    L.append("| Windows Build | " + build + " |")
    L.append("| Source | " + ssn_result["source"] + " |")
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 2. SSN Resolution")
    L.append("")
    L.append("SSN " + str(ssn) + " resolved by parsing ntdll.dll PE export table at runtime.")
    L.append("Extracted from mov eax instruction at start of " + api + " stub.")
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 3. Evasion Confidence")
    L.append("")
    L.append("| EDR Product | Confidence |")
    L.append("|-------------|------------|")
    L.append("| Windows Defender | " + str(conf["windows_defender"]) + "% |")
    L.append("| CrowdStrike Falcon | " + str(conf["crowdstrike_falcon"]) + "% |")
    L.append("| SentinelOne | " + str(conf["sentinelone"]) + "% |")
    L.append("| Overall | " + str(conf["overall"]) + "% |")
    L.append("")
    L.append("Note: " + conf["explanation"])
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 4. Remaining Detection Risks")
    L.append("")
    for risk in risks:
        L.append("### [" + risk["severity"] + "] " + risk["risk"])
        L.append(risk["detail"])
        L.append("")
    L.append("---")
    L.append("")
    L.append("## 5. Defender Perspective")
    L.append("")
    for det in dets:
        L.append("### " + det["method"])
        L.append("**Tool:** " + det["tool"])
        L.append(det["detail"])
        L.append("")
    L.append("---")
    L.append("")
    L.append("## 6. MITRE ATT&CK Mapping")
    L.append("")
    for m in maps:
        L.append("- **" + m["id"] + "** " + m["name"] + " " + m["url"])
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 7. Improvements Beyond v1.0")
    L.append("")
    for imp in imps:
        L.append("### [" + imp["complexity"] + "] " + imp["technique"])
        L.append(imp["detail"])
        L.append("")
    L.append("---")
    L.append("")
    L.append("## Ethical Statement")
    L.append("")
    L.append("Generated for authorised penetration testing only.")
    L.append("SilentGate is open source MIT. Security belongs to everyone.")
    L.append("")
    L.append("— JarDani")
    return "\n".join(L)


def save_report(api_name, report_content):
    os.makedirs(OUTPUT_PATH, exist_ok=True)
    filename = "evasion_report_" + api_name + ".md"
    filepath = os.path.join(OUTPUT_PATH, filename)
    with open(filepath, "w") as f:
        f.write(report_content)
    return filepath


def generate_and_save(api_name, ssn_result, stub_result, intelligence_result):
    report   = generate_report(api_name, ssn_result, stub_result, intelligence_result)
    filepath = save_report(api_name, report)
    print("  [REPORTER] Report saved: " + filepath)
    return filepath